'use client';

import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { useToast } from '@/components/ui/use-toast';
import { Loader2, FileDown, UploadCloud, AlertCircle } from 'lucide-react';
import { motion } from 'framer-motion';
import UploadModal from '@/components/UploadModal';
import { useAuth } from '@/contexts/SupabaseAuthContext';
import { Button } from '@/components/ui/button';
import BackButton from '@/components/BackButton';

export default function Dashboard() {
  const { toast } = useToast();
  const { profile, fetchProfile } = useAuth();
  const [loading, setLoading] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [uploadedFiles, setUploadedFiles] = useState([]);
  const [reportData, setReportData] = useState(null);

  const handleUploadSuccess = async () => {
    toast({
      title: 'Upload Successful!',
      description: "Your deal is being analyzed. You'll be notified once the report is ready.",
    });
    if (profile?.id) {
      await fetchProfile(profile.id);
    }
  };

  const handleUpload = (e) => {
    const files = Array.from(e.target.files);
    const oversized = files.some((f) => f.size > 10 * 1024 * 1024);
    if (oversized) {
      toast({
        title: 'File Too Large',
        description: 'Each file must be under 10 MB.',
        variant: 'destructive',
      });
      return;
    }
    setUploadedFiles(files);
  };

  const handleAnalyze = async () => {
    if (uploadedFiles.length === 0) {
      toast({
        title: 'No Files Selected',
        description: 'Please upload at least one document before generating a report.',
      });
      return;
    }

    setLoading(true);
    try {
      let extracted = {};
      uploadedFiles.forEach((file) => {
        if (file.name.endsWith('.pdf')) extracted.address = '123 Elite St (from PDF)';
        if (file.name.endsWith('.xlsx')) extracted.beds = 4;
        if (file.name.endsWith('.jpg')) extracted.notes = 'Scanned image: Modern kitchen (OCR detected)';
      });

      const coreQuestion =
        prompt('Core Question? (e.g., "5-year IRR projection?")') || '5-year value-add analysis.';
      const investorIQPrompt = `
      ROLE: Institutional real estate analyst.
      GOAL: Generate a professional, data-backed property analysis using the following data: ${JSON.stringify(
        extracted
      )}.
      STYLE: Confident, institutional tone with clear executive summary.
      CORE REQUEST: ${coreQuestion}.
      `;

      const analysis = {
        ...extracted,
        summary: 'Elite property analysis generated by InvestorIQ.',
        valuation: 5000000,
      };

      const { generatePDF } = await import('@/lib/docGenerator');
      await generatePDF(analysis);

      toast({
        title: 'Your InvestorIQ Report is ready!',
        description: 'Your analysis has been completed successfully.',
      });
    } catch (err) {
      console.error(err);
      toast({
        title: 'Analysis Failed',
        description: 'Please try again or contact support if the issue continues.',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <Helmet>
        <title>Dashboard - InvestorIQ</title>
        <meta
          name="description"
          content="Upload property documents and generate InvestorIQ reports. Works for both off-market and MLS properties when documents are available."
        />
      </Helmet>

      <div className="min-h-screen bg-white p-4 sm:p-8 flex flex-col">
        <div className="max-w-4xl mx-auto flex-grow">
          {/* HEADER */}
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex flex-col sm:flex-row sm:items-center justify-between mb-8"
          >
            <div>
              <h1 className="text-3xl sm:text-4xl font-bold text-[#0F172A]">
                Welcome, {profile?.full_name || 'Investor'}!
              </h1>
              <p className="text-slate-600 mt-1 text-base">
                Upload your files below to generate a new InvestorIQ report.
              </p>
            </div>
            <div className="text-right mt-4 sm:mt-0">
              <div className="font-bold text-lg text-slate-700">Report Credits</div>
              <div className="text-3xl font-extrabold text-[#1F8A8A]">
                {profile?.report_credits ?? '...'}
              </div>
            </div>
          </motion.div>

          {/* UPLOAD SECTION */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="bg-white border border-slate-200 rounded-2xl shadow-xl p-6 md:p-8"
          >
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
              <div>
                <h2 className="text-2xl font-bold text-slate-900">Upload Property Documents</h2>
                <p className="text-slate-600 mt-2">
                  Upload PDFs, spreadsheets, or photos of your property.
                  <br />
                  <span className="text-[#1F8A8A] font-semibold">
                    The more data you upload, the better your analysis.
                  </span>{' '}
                  (10 MB max per file)
                </p>
                <p className="text-slate-600 mt-2 text-sm">
                  Works for both off-market and MLS properties when documents are provided by your broker or agent.
                </p>
              </div>

              <Button
                size="lg"
                onClick={() => document.getElementById('fileInput').click()}
                disabled={!profile || profile.report_credits <= 0}
                className="bg-gradient-to-r from-[#1F8A8A] to-[#177272] text-white font-semibold shadow-md hover:scale-105 transition-transform"
              >
                <UploadCloud className="mr-2 h-5 w-5" />
                Upload Files
              </Button>
            </div>

            <input
              id="fileInput"
              type="file"
              multiple
              accept=".pdf,.docx,.xlsx,.xls,.jpg,.jpeg,.png"
              onChange={handleUpload}
              className="hidden"
            />

            {/* FILE PREVIEW */}
            {uploadedFiles.length > 0 && (
              <div className="mt-6 bg-slate-50 border border-slate-200 rounded-xl p-4">
                <h3 className="font-semibold mb-2 text-slate-800">
                  Files Selected ({uploadedFiles.length})
                </h3>
                <ul className="space-y-2 text-sm text-slate-700">
                  {uploadedFiles.map((file, idx) => (
                    <li key={idx} className="flex justify-between border-b border-slate-100 pb-1">
                      <span>{file.name}</span>
                      <span className="text-slate-500 text-xs">
                        {(file.size / 1024 / 1024).toFixed(2)} MB
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* DISCLAIMER */}
            <div className="mt-6 bg-[#1F8A8A]/10 border border-[#1F8A8A]/30 rounded-lg p-4 text-sm text-slate-700">
              <AlertCircle className="inline-block h-5 w-5 text-[#1F8A8A] mr-2" />
              <span className="font-medium">Disclaimer:</span> The quality and accuracy of your report depend on
              the completeness of your uploaded documents.
            </div>

            {/* ACTION */}
            <div className="flex justify-center mt-8">
              <Button
                size="lg"
                onClick={handleAnalyze}
                disabled={uploadedFiles.length === 0 || loading}
                className="px-10 bg-gradient-to-r from-[#1F8A8A] to-[#177272] text-white font-bold hover:opacity-90 transition rounded-xl shadow-md"
              >
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-5 w-5 animate-spin" /> Analyzing...
                  </>
                ) : (
                  'Generate IQ Report'
                )}
              </Button>
            </div>
          </motion.div>

          {/* REPORT SECTION */}
          {reportData && (
            <div className="bg-white rounded-xl shadow-xl p-6 mt-8 border border-slate-200">
              <h2 className="text-2xl font-bold text-[#1F8A8A] mb-4">Report Ready</h2>
              <div className="bg-slate-50 p-4 rounded-lg mb-6 text-sm">
                <p><strong>Address:</strong> {reportData.address}</p>
                <p><strong>Value:</strong> ${reportData.valuation.toLocaleString()}</p>
                <p><strong>Confidence:</strong> {reportData.confidence}%</p>
              </div>

              <Button
                onClick={async () => {
                  if (!reportData) return;
                  setLoading(true);
                  try {
                    const { generatePDF } = await import('@/lib/docGenerator');
                    await generatePDF(reportData);
                    toast({
                      title: 'Your InvestorIQ Report is ready!',
                      description: 'Elite analysis complete.',
                    });
                  } catch (err) {
                    console.error('PDF ERROR:', err);
                    toast({
                      title: 'Download Error',
                      description: 'Please try again later.',
                      variant: 'destructive',
                    });
                  } finally {
                    setLoading(false);
                  }
                }}
                disabled={loading}
                className={`w-full py-4 rounded-lg font-bold text-white text-lg transition-all transform hover:scale-105 ${
                  loading
                    ? 'bg-gray-500 cursor-not-allowed'
                    : 'bg-gradient-to-r from-[#1F8A8A] to-[#177272] shadow-xl'
                }`}
              >
                {loading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin inline" />
                ) : (
                  <FileDown className="mr-2 h-5 w-5 inline" />
                )}
                {loading ? 'Generating PDF...' : 'Download Report'}
              </Button>
            </div>
          )}

          {/* HISTORY SECTION */}
          <div className="mt-8 mb-8">
            <h3 className="text-xl font-bold text-slate-800 mb-4">Analysis History</h3>
            <div className="bg-white rounded-xl shadow-lg p-8 text-center text-slate-500">
              <p>Your analyzed reports will appear here.</p>
              <p className="text-sm">Start by uploading a new deal to see your reports populate.</p>
            </div>
          </div>
        </div>

        {/* FOOTER */}
        <footer className="py-6 border-t bg-white text-center text-slate-500 text-sm">
          © 2025 <span className="font-semibold text-[#1F8A8A]">InvestorIQ</span>. All Rights Reserved.
        </footer>
      </div>

      <UploadModal
        open={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onUpload={handleUploadSuccess}
      />

      <BackButton />
    </>
  );
}
