"""Standalone visual study. Does not import or modify a production report route."""
from pathlib import Path
import base64, json
ROOT=Path(__file__).resolve().parent
# Recorded Stonebridge source fixture, not new underwriting assumptions.
facts=dict(units=64,occupied=60,egi=1500000,opex=555000,noi=945000,gpr=1612800,
           in_place_rent=1432800,market_rent=1718400,expense_lines=535000,
           purchase_price=13500000,current_debt_service=471000,proposed_debt_service=676249.2)
assert facts['egi']-facts['opex']==facts['noi']
assert facts['opex']-facts['expense_lines']==20000
assert facts['in_place_rent']-facts['gpr']==-180000
money=lambda n: '${:,.0f}'.format(n)
fontcss=''
for family,file,weight in [('Study Serif','P052-Roman.otf',400),('Study Sans','NimbusSans-Regular.otf',400),('Study Sans','NimbusSans-Bold.otf',700)]:
 b=Path('/usr/share/fonts/opentype/urw-base35',file).read_bytes()
 fontcss+=f'@font-face{{font-family:"{family}";font-weight:{weight};src:url(data:font/otf;base64,{base64.b64encode(b).decode()}) format("opentype");}}'
css='''
@page{size:letter;margin:0}*{box-sizing:border-box}body{margin:0;color:#203c34;font-family:"Study Sans";font-size:10pt;line-height:1.43;background:#e5e7e4}
.sheet{width:8.5in;height:11in;padding:.53in .62in;position:relative;background:#fff;break-after:page;overflow:visible}.sheet:last-child{break-after:auto}
.serif,h1,h2{font-family:"Study Serif";font-weight:400}h1,h2,h3,p{margin:0}h2{font-size:30pt;line-height:1.1;letter-spacing:-.5pt}h3{font-size:10.5pt;margin:0 0 8pt}p{color:#46554f}.kicker{font-size:8pt;letter-spacing:1.3pt;font-weight:700;color:#65746d}.top{border-bottom:1pt solid #b5a172;padding-bottom:12pt;margin-bottom:22pt;display:table;width:100%}.brand{font-size:15pt;letter-spacing:-.5pt;font-weight:700}.top-right{display:table-cell;text-align:right;font-size:8pt;vertical-align:bottom}.top-left{display:table-cell}.section-title{margin:8pt 0 14pt}.deck{font-size:11pt;line-height:1.5;max-width:455pt}.footer{position:absolute;bottom:24pt;left:44.64pt;right:44.64pt;border-top:.5pt solid #c7cfc9;padding-top:9pt;font-size:7pt;color:#65746d;display:table;width:522.72pt}.footer span{display:table-cell}.footer span:last-child{text-align:right}
.cover{background:#143e34;color:#fff}.cover .top{border-color:#547164}.cover .top-right,.cover .kicker{color:#d3d9cc}.cover .brand{font-size:18pt}.cover-title{margin-top:95pt;font-size:54pt;line-height:1.05;letter-spacing:-1.5pt}.cover-subtitle{font-size:15pt;color:#eee9da;margin-top:21pt}.gold-rule{width:48pt;border-top:2pt solid #bfa367;margin-top:25pt}.cover-tagline{color:#cbd4ca;font-size:11pt;width:310pt;height:40pt;margin-top:29pt;line-height:1.6}.cover-id{font-size:8pt;letter-spacing:1.5pt;color:#cbbd98;margin-top:13pt}.cover-data{display:table;width:100%;border-top:.6pt solid #587567;margin-top:55pt;padding-top:19pt}.cover-data>div{display:table-cell;width:33.3%}.cover-data strong{font-size:25pt;font-weight:400;display:block;color:#fff}.cover-data small{font-size:8pt;color:#d3d9cc}.cover .footer{color:#cbd4ca;border-color:#587567}.cover-note{font-size:8pt;color:#cbd4ca;margin-top:27pt;max-width:430pt}
.decision{margin:18pt 0 18pt;padding:14pt 20pt;background:#edf1ec;border-left:3pt solid #af9557}.decision-label{font-size:8pt;font-weight:700;color:#5a654e;letter-spacing:1pt}.decision-main{font-size:20pt;line-height:1.2;margin:5pt 0 7pt}.decision p{font-size:10pt;line-height:1.5}.metrics{display:table;width:100%;margin:0 0 20pt;border-bottom:1pt solid #b5a172;padding-bottom:19pt}.metric{display:table-cell;width:25%;padding-right:9pt}.metric strong{display:block;font-size:23pt;font-weight:400;letter-spacing:-.7pt}.metric .label{font-size:8pt;color:#61716a;margin-top:4pt}.metric .basis{font-size:7.5pt;color:#61716a;margin-top:2pt}.columns{display:table;width:100%;table-layout:fixed}.col{display:table-cell;vertical-align:top}.main{width:64%;padding-right:24pt}.side{width:36%;padding-left:20pt;border-left:.5pt solid #c7cfc9}.row{border-top:.5pt solid #d7ddd8;padding:8pt 0}.row:first-of-type{border-top:0}.row-title{font-weight:700;font-size:10pt;color:#203c34;margin-bottom:4pt}.row p,.side p{font-size:9.6pt;line-height:1.48}.index{font-size:8pt;color:#917941;margin-right:7pt}.side-stat{font-size:25pt;color:#203c34;line-height:1.15;margin:8pt 0 5pt}.small{font-size:8pt;color:#61716a;line-height:1.5}.source{font-size:7.5pt;color:#64736b;line-height:1.45;margin-top:14pt;border-top:.5pt solid #d7ddd8;padding-top:9pt}.section-rule{border-top:1pt solid #b5a172;padding-top:14pt;margin-top:18pt}.chart-title{display:table;width:100%;margin-bottom:5pt}.chart-title>*{display:table-cell}.chart-title small{text-align:right;font-size:8pt;color:#64736b}.hero-chart{width:100%;height:188pt;display:block;margin:3pt 0 14pt}table{width:100%;border-collapse:collapse;font-size:9pt}th{text-align:left;font-size:8pt;color:#61716a;padding:8pt 0;border-bottom:1pt solid #6b8072;font-weight:400}td{padding:9pt 0;border-bottom:.5pt solid #d7ddd8}th:last-child,td:last-child{text-align:right}tr.total td{font-weight:700;border-top:1pt solid #6b8072;border-bottom:1pt solid #6b8072;background:#edf1ec}.operating .section-title{margin-bottom:10pt}.operating .deck{font-size:10.5pt}.operating .source{margin-top:16pt}
'''
def footer(product,n):
 return f'<div class="footer"><span>InvestorIQ / {product}</span><span>Design prototype · 05 September 2026</span><span>{n:02d}</span></div>'
def top(product):
 return f'<div class="top"><div class="top-left brand">InvestorIQ<span style="color:#b79e62">.</span></div><div class="top-right">Stonebridge Lofts<br>{product} Report</div></div>'
def cover(product,n):
 tagline={'Screening':'An operating view for the next diligence decision.','Underwriting':'An evidence-led view of operations, financing and acquisition diligence.'}[product]
 return f'''<section class="sheet cover">{top(product)}<div class="kicker">PROPERTY INTELLIGENCE</div><h1 class="cover-title">Stonebridge<br>Lofts</h1><div class="gold-rule"></div><p class="cover-subtitle">InvestorIQ {product} Report</p><div class="cover-id">MULTIFAMILY / 64 UNITS</div><p class="cover-tagline">{tagline}</p><div class="cover-data"><div><strong>64</strong><small>Total units</small></div><div><strong>93.8%</strong><small>Physical occupancy</small></div><div><strong>$945,000</strong><small>T12 net operating income</small></div></div><p class="cover-note">Prepared from the supplied property documents.<br>Source reconciliation matters are identified within this report.</p>{footer(product,n)}</section>'''
def metric(v,l,b):return f'<div class="metric"><strong>{v}</strong><div class="label">{l}</div><div class="basis">{b}</div></div>'
def row(n,title,body):return f'<div class="row"><div class="row-title"><span class="index">{n}</span>{title}</div><p>{body}</p></div>'
screen=f'''<section class="sheet">{top('Screening')}<div class="kicker">01 / DECISION SUMMARY</div><h2 class="section-title">The operating picture.</h2><p class="deck">Recorded operations support a useful first view. Two source differences need clarification before progressing diligence.</p><div class="decision"><div class="decision-label">SCREENING DISPOSITION</div><div class="decision-main">Hold for source reconciliation</div><p>Confirm the relationship between the rent roll and trailing rental income, and obtain the missing operating-expense detail.</p></div><div class="metrics">{metric('$945K','T12 net operating income','Reported operating basis')}{metric('93.8%','Physical occupancy','60 of 64 units')}{metric('63.0%','NOI margin','NOI / effective gross income')}{metric('$180K','Rent-basis difference','Rent roll below T12 GPR')}</div><div class="columns"><div class="col main"><h3>What warrants attention</h3>{row('01','Rental sources use different bases','Annual in-place rent of $1,432,800 is $180,000 below T12 gross potential rent of $1,612,800. The cause is not established by this comparison.')}{row('02','Expense detail does not fully reconcile','Listed operating expenses total $535,000; the source states $555,000. The $20,000 difference remains unresolved.')}{row('03','Keep the reported operating baseline','Effective gross income of $1,500,000 less stated expenses of $555,000 supports $945,000 of NOI. Do not replace the source total with incomplete detail.')}</div><div class="col side"><div class="kicker">NEXT DILIGENCE GATE</div><div class="side-stat">Two questions.</div><p>Explain the rental-period and rent-definition differences.<br><br>Supply the expense schedule supporting the stated total.</p><div class="section-rule"><h3>Read-through</h3><p>These disclosures accompany the operating figures. They do not establish an investment recommendation.</p></div></div></div><div class="source">Basis: Stonebridge T12 and rent roll. Occupancy: 60 / 64. NOI margin: $945,000 / $1,500,000. Dollar differences compare stated document bases; causes require reconciliation.</div>{footer('Screening',2)}</section>'''
uw=f'''<section class="sheet">{top('Underwriting')}<div class="kicker">01 / DECISION SUMMARY</div><h2 class="section-title">Operations into capital.</h2><p class="deck">The same operating baseline now sits alongside documented acquisition and financing terms, with source limitations carried forward.</p><div class="decision"><div class="decision-label">UNDERWRITING STATUS</div><div class="decision-main">Source reconciliation required</div><p>Retain the $945,000 reported NOI basis. Resolve the rent and expense differences before relying on a fully reconciled operating case.</p></div><div class="metrics">{metric('$945K','T12 net operating income','Same Screening baseline')}{metric('$13.50M','Purchase price','Documented acquisition input')}{metric('7.00%','Going-in cap rate','NOI / purchase price')}{metric('1.40x','Proposed debt coverage','NOI / proposed annual service')}</div><div class="columns"><div class="col main"><h3>What the additional evidence establishes</h3>{row('01','Financing changes the coverage position','Current annual service of $471,000 produces 2.01x coverage. Proposed service of $676,249 produces 1.40x on the same NOI.')}{row('02','A documented acquisition basis','The $13,500,000 purchase input equates to $210,938 per unit and a 7.00% going-in cap rate. Both use the reported operating basis.')}{row('03','Open items carry into the deeper review','The $180,000 rental-basis difference and $20,000 expense-detail gap remain unresolved after the supporting-document review.')}</div><div class="col side"><div class="kicker">OPERATING CONTINUITY</div><div class="side-stat">64 units.</div><p>60 occupied / 4 vacant<br>93.8% physical occupancy<br><br>T12 effective gross income<br><b>$1,500,000</b><br><br>Stated operating expenses<br><b>$555,000</b></p><div class="section-rule"><h3>Coverage basis</h3><p>Keep current and proposed debt coverage separate.</p></div></div></div><div class="source">Basis: same Stonebridge T12 and rent roll, plus documented acquisition and debt inputs. Proposed service uses $9,450,000 at 5.95%, amortized over 30 years. No investment approval is expressed.</div>{footer('Underwriting',4)}</section>'''
# Waterfall uses a common zero and a linear dollar-to-height scale.
scale=130/1500000; baseline=165
y=lambda v: baseline-v*scale
svg=f'''<svg class="hero-chart" viewBox="0 0 640 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Effective gross income of 1.5 million dollars less 555 thousand dollars of operating expenses equals 945 thousand dollars of net operating income."><g font-family="Study Sans" font-size="11" fill="#61716a"><path d="M55 165H615 M55 121.667H615 M55 78.333H615 M55 35H615" stroke="#e3e7e1" stroke-width="1"/><text x="40" y="169" text-anchor="end">0</text><text x="40" y="125.667" text-anchor="end">0.5</text><text x="40" y="82.333" text-anchor="end">1.0</text><text x="40" y="39" text-anchor="end">1.5</text><text x="4" y="17">$M</text></g><rect x="82" y="{y(facts['egi'])}" width="130" height="{facts['egi']*scale}" fill="#244e41"/><path d="M212 35H280 M410 {y(facts['noi'])}H475" stroke="#8f9f93" stroke-dasharray="4 4"/><rect x="280" y="35" width="130" height="{facts['opex']*scale}" fill="#b5a172"/><rect x="475" y="{y(facts['noi'])}" width="130" height="{facts['noi']*scale}" fill="#143e34"/><g font-family="Study Sans" font-size="20" fill="#fff" text-anchor="middle"><text x="147" y="65">$1,500,000</text><text x="345" y="65" fill="#203c34">($555,000)</text><text x="540" y="{y(facts['noi'])+36}">$945,000</text></g><g font-family="Study Sans" font-size="12" fill="#203c34" text-anchor="middle"><text x="147" y="191">Effective gross income</text><text x="345" y="191">Operating expenses</text><text x="540" y="191">Net operating income</text></g><g font-family="Study Sans" font-size="10" fill="#64736b" text-anchor="middle"><text x="147" y="212">Reported T12 income</text><text x="345" y="212">37.0% of EGI</text><text x="540" y="212">63.0% of EGI</text></g></svg>'''
operating=f'''<section class="sheet operating">{top('Underwriting')}<div class="kicker">02 / OPERATING ANALYSIS</div><h2 class="section-title">From income to NOI.</h2><p class="deck">Reported net operating income retains 63 cents of each dollar of effective gross income, before debt service.</p><div class="section-rule"><div class="chart-title"><h3>T12 earnings bridge</h3><small>Annual dollars / reported operating basis</small></div>{svg}</div><div class="columns"><div class="col main"><table><thead><tr><th>Operating statement</th><th>Annual amount</th></tr></thead><tbody><tr><td>Effective gross income</td><td>$1,500,000</td></tr><tr><td>Operating expenses</td><td>($555,000)</td></tr><tr class="total"><td>Net operating income</td><td>$945,000</td></tr><tr><td>NOI per unit</td><td>$14,766</td></tr></tbody></table></div><div class="col side"><div class="kicker">SOURCE DETAIL GAP</div><div class="side-stat">$20,000</div><p>Listed expenses are below the stated total. The earnings bridge retains stated expenses; it does not substitute the incomplete schedule.</p></div></div><div class="section-rule"><h3>The reconciliation that still matters</h3><p>Resolve the $20,000 gap before revising NOI. Substituting the incomplete $535,000 expense schedule would overstate NOI by the same amount.</p></div><div class="source">Basis: Stonebridge T12. NOI = $1,500,000 - $555,000. NOI per unit = $945,000 / 64, rounded to whole dollars. The waterfall uses a common linear dollar scale.</div>{footer('Underwriting',5)}</section>'''
html='<!doctype html><html lang="en"><head><meta charset="utf-8"><title>InvestorIQ - Stonebridge publication design study</title><style>'+fontcss+css+'</style></head><body>'+cover('Screening',1)+screen+cover('Underwriting',3)+uw+operating+'</body></html>'
(ROOT/'prototype.html').write_text(html)
(ROOT/'source-facts.json').write_text(json.dumps(facts,indent=2)+'\n')
(ROOT/'earnings-bridge.svg').write_text(svg)
print(ROOT/'prototype.html')
